[2024-04-29T07:53:31.858+0000] {processor.py:157} INFO - Started process (PID=10912) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:53:31.859+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:53:31.860+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:53:31.859+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:53:31.868+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:53:31.861+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 4
    from airflow.
                 ^
SyntaxError: invalid syntax
[2024-04-29T07:53:31.869+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:53:31.902+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.046 seconds
[2024-04-29T07:53:41.189+0000] {processor.py:157} INFO - Started process (PID=10979) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:53:41.189+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:53:41.190+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:53:41.190+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:53:41.192+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:53:41.192+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 4
    from airflow.operators.bash 
                                ^
SyntaxError: invalid syntax
[2024-04-29T07:53:41.193+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:53:41.225+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.039 seconds
[2024-04-29T07:54:00.366+0000] {processor.py:157} INFO - Started process (PID=11146) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:54:00.366+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:54:00.367+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:54:00.367+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:54:00.371+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:54:00.369+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 7, in <module>
    defau
NameError: name 'defau' is not defined
[2024-04-29T07:54:00.372+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:54:00.406+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.043 seconds
[2024-04-29T07:54:20.335+0000] {processor.py:157} INFO - Started process (PID=11288) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:54:20.336+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:54:20.336+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:54:20.336+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:54:20.340+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:54:20.339+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 9
    'depends_on'
               ^
SyntaxError: ':' expected after dictionary key
[2024-04-29T07:54:20.340+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:54:20.381+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.049 seconds
[2024-04-29T07:54:37.126+0000] {processor.py:157} INFO - Started process (PID=11430) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:54:37.127+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:54:37.127+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:54:37.127+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:54:37.130+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:54:37.129+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 10
    'emai'
         ^
SyntaxError: ':' expected after dictionary key
[2024-04-29T07:54:37.130+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:54:37.163+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.039 seconds
[2024-04-29T07:54:54.024+0000] {processor.py:157} INFO - Started process (PID=11560) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:54:54.024+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:54:54.025+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:54:54.025+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:54:54.027+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:54:54.026+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 11
    'email_on_retry'
                   ^
SyntaxError: ':' expected after dictionary key
[2024-04-29T07:54:54.027+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:54:54.060+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.039 seconds
[2024-04-29T07:55:10.773+0000] {processor.py:157} INFO - Started process (PID=11673) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:55:10.773+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:55:10.774+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:55:10.774+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:55:10.776+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:55:10.806+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.035 seconds
[2024-04-29T07:55:28.958+0000] {processor.py:157} INFO - Started process (PID=11806) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:55:28.959+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:55:28.960+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:55:28.960+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:55:28.963+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:55:28.962+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 14
    'start_date'
               ^
SyntaxError: ':' expected after dictionary key
[2024-04-29T07:55:28.963+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:55:28.999+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.044 seconds
[2024-04-29T07:55:46.887+0000] {processor.py:157} INFO - Started process (PID=11942) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:55:46.887+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:55:46.888+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:55:46.888+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:55:46.891+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:55:46.890+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 14, in <module>
    'start_date':datetime(2024,)
TypeError: function missing required argument 'month' (pos 2)
[2024-04-29T07:55:46.891+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:55:46.924+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.040 seconds
[2024-04-29T07:56:05.082+0000] {processor.py:157} INFO - Started process (PID=12087) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:56:05.083+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:56:05.083+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:56:05.083+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:56:05.086+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:56:05.085+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 17
    with DAG
            ^
SyntaxError: expected ':'
[2024-04-29T07:56:05.086+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:56:05.125+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.046 seconds
[2024-04-29T07:56:25.609+0000] {processor.py:157} INFO - Started process (PID=12224) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:56:25.610+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:56:25.610+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:56:25.610+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:56:25.613+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:56:25.612+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 20
    )
     ^
SyntaxError: expected ':'
[2024-04-29T07:56:25.613+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:56:25.648+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.043 seconds
[2024-04-29T07:56:46.872+0000] {processor.py:157} INFO - Started process (PID=12379) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:56:46.873+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:56:46.873+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:56:46.873+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:56:46.876+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:56:46.875+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 19
    'description=''
                  ^
SyntaxError: unterminated string literal (detected at line 19)
[2024-04-29T07:56:46.876+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:56:46.909+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.039 seconds
[2024-04-29T07:57:07.163+0000] {processor.py:157} INFO - Started process (PID=12544) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:57:07.164+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:57:07.165+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:57:07.164+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:57:07.168+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:57:07.167+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 21
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 17
[2024-04-29T07:57:07.169+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:57:07.208+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.048 seconds
[2024-04-29T07:57:28.677+0000] {processor.py:157} INFO - Started process (PID=12699) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:57:28.678+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:57:28.679+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:57:28.678+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:57:28.681+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:57:28.680+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 23
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 17
[2024-04-29T07:57:28.681+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:57:28.714+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.039 seconds
[2024-04-29T07:57:49.048+0000] {processor.py:157} INFO - Started process (PID=12854) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:57:49.049+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:57:49.049+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:57:49.049+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:57:49.052+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:57:49.051+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    )
    ^
SyntaxError: invalid syntax
[2024-04-29T07:57:49.052+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:57:49.099+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.053 seconds
[2024-04-29T07:58:09.577+0000] {processor.py:157} INFO - Started process (PID=13008) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:58:09.578+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:58:09.578+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:58:09.578+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:58:09.584+0000] {processor.py:836} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:58:09.705+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:58:09.704+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:one_task_dag
[2024-04-29T07:58:09.736+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:58:09.736+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:one_task_dag
[2024-04-29T07:58:09.761+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:58:09.761+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:one_task_dag
[2024-04-29T07:58:09.770+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:58:09.770+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-04-29T07:58:09.777+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:58:09.777+0000] {dag.py:2763} INFO - Creating ORM DAG for one_task_dag
[2024-04-29T07:58:09.784+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:58:09.784+0000] {dag.py:3504} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2024-04-29T07:58:09.839+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.264 seconds
[2024-04-29T07:58:31.193+0000] {processor.py:157} INFO - Started process (PID=13166) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:58:31.194+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:58:31.195+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:58:31.194+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:58:31.197+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:58:31.197+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!"'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T07:58:31.198+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:58:31.230+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.039 seconds
[2024-04-29T07:59:07.560+0000] {processor.py:157} INFO - Started process (PID=13410) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:59:07.561+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:59:07.561+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:59:07.561+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:59:07.564+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:59:07.563+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T07:59:07.564+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:59:07.604+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.047 seconds
[2024-04-29T07:59:43.134+0000] {processor.py:157} INFO - Started process (PID=13669) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:59:43.135+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T07:59:43.135+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:59:43.135+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:59:43.138+0000] {logging_mixin.py:150} INFO - [2024-04-29T07:59:43.137+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T07:59:43.138+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T07:59:43.169+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.037 seconds
[2024-04-29T08:00:16.850+0000] {processor.py:157} INFO - Started process (PID=13891) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:00:16.850+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:00:16.851+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:00:16.851+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:00:16.854+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:00:16.853+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:00:16.854+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:00:16.886+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.038 seconds
[2024-04-29T08:00:50.591+0000] {processor.py:157} INFO - Started process (PID=14154) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:00:50.592+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:00:50.592+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:00:50.592+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:00:50.595+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:00:50.594+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:00:50.595+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:00:50.627+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.038 seconds
[2024-04-29T08:01:27.681+0000] {processor.py:157} INFO - Started process (PID=14397) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:01:27.681+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:01:27.682+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:01:27.682+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:01:27.684+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:01:27.684+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:01:27.685+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:01:27.715+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.037 seconds
[2024-04-29T08:02:02.848+0000] {processor.py:157} INFO - Started process (PID=14653) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:02:02.849+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:02:02.850+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:02:02.849+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:02:02.852+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:02:02.851+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:02:02.852+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:02:02.888+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.042 seconds
[2024-04-29T08:02:36.470+0000] {processor.py:157} INFO - Started process (PID=14877) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:02:36.471+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:02:36.471+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:02:36.471+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:02:36.474+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:02:36.473+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:02:36.474+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:02:36.506+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.038 seconds
[2024-04-29T08:03:08.547+0000] {processor.py:157} INFO - Started process (PID=15098) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:03:08.547+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:03:08.548+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:03:08.548+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:03:08.550+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:03:08.550+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:03:08.551+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:03:08.582+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.037 seconds
[2024-04-29T08:03:41.587+0000] {processor.py:157} INFO - Started process (PID=15321) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:03:41.587+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:03:41.588+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:03:41.588+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:03:41.591+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:03:41.590+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:03:41.591+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:03:41.627+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.042 seconds
[2024-04-29T08:04:17.733+0000] {processor.py:157} INFO - Started process (PID=15571) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:04:17.733+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:04:17.734+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:04:17.734+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:04:17.736+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:04:17.736+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:04:17.737+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:04:17.768+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.038 seconds
[2024-04-29T08:04:53.890+0000] {processor.py:157} INFO - Started process (PID=15808) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:04:53.890+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:04:53.891+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:04:53.891+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:04:53.894+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:04:53.893+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:04:53.895+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:04:53.929+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.041 seconds
[2024-04-29T08:05:27.918+0000] {processor.py:157} INFO - Started process (PID=16058) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:05:27.919+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:05:27.919+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:05:27.919+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:05:27.922+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:05:27.921+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:05:27.922+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:05:27.955+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.039 seconds
[2024-04-29T08:06:02.502+0000] {processor.py:157} INFO - Started process (PID=16296) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:06:02.503+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:06:02.504+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:06:02.503+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:06:02.506+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:06:02.505+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:06:02.507+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:06:02.538+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.038 seconds
[2024-04-29T08:06:38.671+0000] {processor.py:157} INFO - Started process (PID=16545) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:06:38.672+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:06:38.673+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:06:38.672+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:06:38.675+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:06:38.675+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:06:38.675+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:06:38.707+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.038 seconds
[2024-04-29T08:07:12.834+0000] {processor.py:157} INFO - Started process (PID=16775) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:07:12.834+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:07:12.835+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:07:12.835+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:07:12.837+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:07:12.837+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:07:12.838+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:07:12.869+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.038 seconds
[2024-04-29T08:07:45.963+0000] {processor.py:157} INFO - Started process (PID=16996) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:07:45.964+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:07:45.964+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:07:45.964+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:07:45.967+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:07:45.966+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:07:45.967+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:07:45.998+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.037 seconds
[2024-04-29T08:08:22.071+0000] {processor.py:157} INFO - Started process (PID=17254) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:08:22.071+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:08:22.072+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:08:22.072+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:08:22.074+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:08:22.074+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:08:22.075+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:08:22.106+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.038 seconds
[2024-04-29T08:08:53.032+0000] {processor.py:157} INFO - Started process (PID=17468) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:08:53.033+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:08:53.034+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:08:53.033+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:08:53.036+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:08:53.036+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:08:53.037+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:08:53.081+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.051 seconds
[2024-04-29T08:09:28.303+0000] {processor.py:157} INFO - Started process (PID=17699) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:09:28.304+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:09:28.305+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:09:28.305+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:09:28.309+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:09:28.308+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:09:28.309+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:09:28.346+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.045 seconds
[2024-04-29T08:10:07.847+0000] {processor.py:157} INFO - Started process (PID=17977) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:10:07.847+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:10:07.848+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:10:07.848+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:10:07.850+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:10:07.850+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:10:07.851+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:10:07.881+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.037 seconds
[2024-04-29T08:10:40.430+0000] {processor.py:157} INFO - Started process (PID=18207) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:10:40.431+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:10:40.432+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:10:40.431+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:10:40.435+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:10:40.434+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:10:40.436+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:10:40.473+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.047 seconds
[2024-04-29T08:11:10.904+0000] {processor.py:157} INFO - Started process (PID=18406) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:11:10.904+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:11:10.905+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:11:10.905+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:11:10.909+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:11:10.908+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:11:10.909+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:11:10.948+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.048 seconds
[2024-04-29T08:11:44.486+0000] {processor.py:157} INFO - Started process (PID=18649) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:11:44.487+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:11:44.487+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:11:44.487+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:11:44.490+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:11:44.489+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:11:44.490+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:11:44.521+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.037 seconds
[2024-04-29T08:12:22.280+0000] {processor.py:157} INFO - Started process (PID=18894) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:12:22.281+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:12:22.282+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:12:22.282+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:12:22.292+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:12:22.287+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:12:22.292+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:12:22.360+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.083 seconds
[2024-04-29T08:12:57.703+0000] {processor.py:157} INFO - Started process (PID=19147) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:12:57.704+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:12:57.704+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:12:57.704+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:12:57.707+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:12:57.706+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:12:57.707+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:12:57.740+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.039 seconds
[2024-04-29T08:13:33.356+0000] {processor.py:157} INFO - Started process (PID=19385) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:13:33.358+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:13:33.358+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:13:33.358+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:13:33.361+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:13:33.360+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:13:33.361+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:13:33.395+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.042 seconds
[2024-04-29T08:14:06.703+0000] {processor.py:157} INFO - Started process (PID=19626) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:14:06.704+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:14:06.705+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:14:06.704+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:14:06.707+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:14:06.706+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:14:06.707+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:14:06.740+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.038 seconds
[2024-04-29T08:14:44.828+0000] {processor.py:157} INFO - Started process (PID=19892) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:14:44.829+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:14:44.829+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:14:44.829+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:14:44.833+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:14:44.832+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/work'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:14:44.834+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:14:44.870+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.046 seconds
[2024-04-29T08:15:02.435+0000] {processor.py:157} INFO - Started process (PID=20032) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:15:02.436+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:15:02.436+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:15:02.436+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:15:02.439+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:15:02.438+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/workspaces/hands-on-introduction-data-engineering-4395021/'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:15:02.439+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:15:02.471+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.039 seconds
[2024-04-29T08:15:21.370+0000] {processor.py:157} INFO - Started process (PID=20171) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:15:21.370+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:15:21.371+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:15:21.371+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:15:21.374+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:15:21.373+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/workspaces/hands-on-introduction-data-engineering-4395021/02-05b/lab/'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:15:21.374+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:15:21.405+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.038 seconds
[2024-04-29T08:15:40.974+0000] {processor.py:157} INFO - Started process (PID=20315) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:15:40.974+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:15:40.975+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:15:40.975+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:15:40.979+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:15:40.978+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/workspaces/hands-on-introduction-data-engineering-4395021/02-05b/lab/create-this-file.txt'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:15:40.980+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:15:41.015+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.043 seconds
[2024-04-29T08:16:16.606+0000] {processor.py:157} INFO - Started process (PID=20745) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:16:16.607+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:16:16.608+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:16:16.607+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:16:16.610+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:16:16.610+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py", line 26
    bash_command='echo "Hello Linkedin Learning!" >/workspaces/hands-on-introduction-data-engineering-4395021/02-05b/lab/create-this-file.txt'
                 
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-04-29T08:16:16.610+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:16:16.643+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.039 seconds
[2024-04-29T08:16:34.403+0000] {processor.py:157} INFO - Started process (PID=20908) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:16:34.403+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:16:34.404+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:16:34.404+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:16:34.412+0000] {processor.py:836} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:16:34.596+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:16:34.596+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-04-29T08:16:34.610+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:16:34.610+0000] {dag.py:3504} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2024-04-29T08:16:34.671+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.271 seconds
[2024-04-29T08:17:09.110+0000] {processor.py:157} INFO - Started process (PID=21208) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:17:09.111+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:17:09.112+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:17:09.111+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:17:09.118+0000] {processor.py:836} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:17:09.135+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:17:09.135+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-04-29T08:17:09.158+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:17:09.158+0000] {dag.py:3504} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2024-04-29T08:17:09.211+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.104 seconds
[2024-04-29T08:17:32.756+0000] {processor.py:157} INFO - Started process (PID=21466) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:17:32.757+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:17:32.758+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:17:32.757+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:17:32.769+0000] {processor.py:836} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:17:32.792+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:17:32.792+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-04-29T08:17:32.837+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:17:32.837+0000] {dag.py:3504} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2024-04-29T08:17:32.890+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.137 seconds
[2024-04-29T08:18:03.943+0000] {processor.py:157} INFO - Started process (PID=21674) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:18:03.944+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:18:03.944+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:18:03.944+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:18:03.952+0000] {processor.py:836} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:18:03.967+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:18:03.967+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-04-29T08:18:03.983+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:18:03.982+0000] {dag.py:3504} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2024-04-29T08:18:04.018+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.076 seconds
[2024-04-29T08:18:34.292+0000] {processor.py:157} INFO - Started process (PID=21858) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:18:34.292+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:18:34.293+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:18:34.293+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:18:34.301+0000] {processor.py:836} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:18:34.316+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:18:34.316+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-04-29T08:18:34.332+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:18:34.332+0000] {dag.py:3504} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2024-04-29T08:18:34.369+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.079 seconds
[2024-04-29T08:19:04.653+0000] {processor.py:157} INFO - Started process (PID=22029) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:19:04.654+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:19:04.655+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:19:04.654+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:19:04.670+0000] {processor.py:836} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:19:04.724+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:19:04.724+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-04-29T08:19:04.763+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:19:04.763+0000] {dag.py:3504} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2024-04-29T08:19:04.801+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.152 seconds
[2024-04-29T08:19:34.964+0000] {processor.py:157} INFO - Started process (PID=22217) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:19:34.965+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:19:34.965+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:19:34.965+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:19:34.974+0000] {processor.py:836} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:19:34.989+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:19:34.989+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-04-29T08:19:35.004+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:19:35.004+0000] {dag.py:3504} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2024-04-29T08:19:35.040+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.078 seconds
[2024-04-29T08:20:05.324+0000] {processor.py:157} INFO - Started process (PID=22399) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:20:05.325+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:20:05.326+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:20:05.325+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:20:05.333+0000] {processor.py:836} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:20:05.350+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:20:05.350+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-04-29T08:20:05.366+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:20:05.366+0000] {dag.py:3504} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2024-04-29T08:20:05.402+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.082 seconds
[2024-04-29T08:20:36.413+0000] {processor.py:157} INFO - Started process (PID=22578) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:20:36.414+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:20:36.414+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:20:36.414+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:20:36.422+0000] {processor.py:836} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:20:36.438+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:20:36.438+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-04-29T08:20:36.453+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:20:36.453+0000] {dag.py:3504} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2024-04-29T08:20:36.487+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.076 seconds
[2024-04-29T08:21:02.676+0000] {processor.py:157} INFO - Started process (PID=22767) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:21:02.677+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:21:02.678+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:21:02.677+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:21:02.686+0000] {processor.py:836} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:21:02.776+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:21:02.775+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-04-29T08:21:02.791+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:21:02.791+0000] {dag.py:3504} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2024-04-29T08:21:02.828+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.154 seconds
[2024-04-29T08:21:27.801+0000] {processor.py:157} INFO - Started process (PID=22915) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:21:27.801+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:21:27.802+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:21:27.802+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:21:27.810+0000] {processor.py:836} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:21:27.817+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:21:27.817+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-04-29T08:21:27.833+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:21:27.833+0000] {dag.py:3504} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2024-04-29T08:21:27.869+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.071 seconds
[2024-04-29T08:21:58.577+0000] {processor.py:157} INFO - Started process (PID=23111) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:21:58.578+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:21:58.578+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:21:58.578+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:21:58.587+0000] {processor.py:836} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:21:58.738+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:21:58.738+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-04-29T08:21:58.764+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:21:58.764+0000] {dag.py:3504} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2024-04-29T08:21:58.806+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.232 seconds
[2024-04-29T08:22:29.244+0000] {processor.py:157} INFO - Started process (PID=23293) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:22:29.244+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:22:29.245+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:22:29.245+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:22:29.253+0000] {processor.py:836} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:22:29.269+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:22:29.269+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-04-29T08:22:29.284+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:22:29.284+0000] {dag.py:3504} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2024-04-29T08:22:29.317+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.075 seconds
[2024-04-29T08:22:59.725+0000] {processor.py:157} INFO - Started process (PID=23476) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:22:59.725+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:22:59.726+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:22:59.726+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:22:59.734+0000] {processor.py:836} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:22:59.750+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:22:59.750+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-04-29T08:22:59.766+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:22:59.766+0000] {dag.py:3504} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2024-04-29T08:22:59.802+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.079 seconds
[2024-04-29T08:23:30.191+0000] {processor.py:157} INFO - Started process (PID=23666) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:23:30.192+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py for tasks to queue
[2024-04-29T08:23:30.193+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:23:30.192+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:23:30.201+0000] {processor.py:836} INFO - DAG(s) dict_keys(['one_task_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py
[2024-04-29T08:23:30.216+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:23:30.216+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-04-29T08:23:30.231+0000] {logging_mixin.py:150} INFO - [2024-04-29T08:23:30.231+0000] {dag.py:3504} INFO - Setting next_dagrun for one_task_dag to None, run_after=None
[2024-04-29T08:23:30.264+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/one_task_dag.py took 0.075 seconds
