[2024-04-29T08:19:08.101+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: one_task_dag.one_task manual__2024-04-29T08:19:04.528297+00:00 [queued]>
[2024-04-29T08:19:08.106+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: one_task_dag.one_task manual__2024-04-29T08:19:04.528297+00:00 [queued]>
[2024-04-29T08:19:08.106+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-04-29T08:19:08.143+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): one_task> on 2024-04-29 08:19:04.528297+00:00
[2024-04-29T08:19:08.146+0000] {standard_task_runner.py:57} INFO - Started process 22049 to run task
[2024-04-29T08:19:08.149+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'one_task_dag', 'one_task', 'manual__2024-04-29T08:19:04.528297+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/one_task_dag.py', '--cfg-path', '/tmp/tmpvv8bd1gs']
[2024-04-29T08:19:08.149+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask one_task
[2024-04-29T08:19:08.197+0000] {task_command.py:410} INFO - Running <TaskInstance: one_task_dag.one_task manual__2024-04-29T08:19:04.528297+00:00 [running]> on host codespaces-910724
[2024-04-29T08:19:08.282+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Shiraj' AIRFLOW_CTX_DAG_ID='one_task_dag' AIRFLOW_CTX_TASK_ID='one_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T08:19:04.528297+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T08:19:04.528297+00:00'
[2024-04-29T08:19:08.283+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-29T08:19:08.283+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Hello Linkedin Learning!" >/workspaces/hands-on-introduction-data-engineering-4395021/02-05b/lab/create-this-file.txt']
[2024-04-29T08:19:08.293+0000] {subprocess.py:86} INFO - Output:
[2024-04-29T08:19:08.293+0000] {subprocess.py:93} INFO - /usr/bin/bash: /workspaces/hands-on-introduction-data-engineering-4395021/02-05b/lab/create-this-file.txt: No such file or directory
[2024-04-29T08:19:08.294+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-29T08:19:08.298+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-29T08:19:08.300+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=one_task_dag, task_id=one_task, execution_date=20240429T081904, start_date=20240429T081908, end_date=20240429T081908
[2024-04-29T08:19:08.329+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task one_task (Bash command failed. The command returned a non-zero exit code 1.; 22049)
[2024-04-29T08:19:08.360+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-04-29T08:19:08.370+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
